# -*- mode: ruby -*- 
# vi: set ft=ruby : vsa
Vagrant.configure(2) do |config| 
 config.vm.box = "centos/7" 
 config.vm.box_version = "2004.01" 
 config.vm.provider "virtualbox" do |v| 
 v.memory = 512 
 v.cpus = 1 
 end 
 config.vm.define "nfss" do |nfss| 
 nfss.vm.network "private_network", ip: "192.168.56.110"
 nfss.vm.provision "shell", path: "nfs_server_script.sh" 
 nfss.vm.hostname = "nfss" 
 end 
 config.vm.define "nfsc" do |nfsc| 
 nfsc.vm.network "private_network", ip: "192.168.56.111" 
 nfsc.vm.provision "shell", path: "nfs_client_script.sh"
 nfsc.vm.hostname = "nfsc" 
 end 
end 



