# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "vpn.yml"
        ansible.become_user = "root" 
        ansible.compatibility_mode = "2.0"
        ansible.become = true
      end
    config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    end
    config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.20"
    end


end