---
- name: configure VPN
  hosts: all
  handlers:
  - name: RESTART OPENVPN 
    ansible.builtin.service:
      name: openvpn@{{ansible_hostname}}
      state: restarted
      enabled: yes       
  tasks:
  - name: install release
    yum:
      name: epel-release
      state: present
      update_cache: yes

  - name: install soft
    yum:
      name: openvpn, iperf, vim
      state: present
      update_cache: yes 
  
  - name: selinux
    shell: 'setenforce 0'   

  - name: generate key
    shell: 'openvpn --genkey --secret /etc/openvpn/static.key' 
    when: (ansible_hostname == "server") 

  - name: fitch key 
    fetch:
      src: /etc/openvpn/static.key
      dest: static.key
      flat: yes
    when: (ansible_hostname == "server")

  - name: copy key on client
    copy:
      src: static.key
      dest: /etc/openvpn/static.key
      mode: 0644  
      group: root
      owner: root
    when: (ansible_hostname == "client")

  - name: create server.conf
    copy:
      dest: /etc/openvpn/server.conf
      mode: 0644  
      group: root
      owner: root
      content: |
        dev tap
        ifconfig 10.10.10.1 255.255.255.0
        topology subnet
        secret /etc/openvpn/static.key
        comp-lzo
        status /var/log/openvpn-status.log
        log /var/log/openvpn.log
        verb 3
    when: (ansible_hostname == "server") 
  - name: create service
    copy:
      dest: /etc/systemd/system/openvpn@.{{ansible_hostname}}
      mode: 0644  
      group: root
      owner: root
      content: |    
        [Unit]
        Description=OpenVPN Tunneling Application On %I
        After=network.target

        [Service]
        Type=notify
        PrivateTmp=true
        ExecStart=/usr/sbin/openvpn --cd /etc/openvpn/ --config %i.conf

        [Install]
        WantedBy=multi-user.target  
    notify: RESTART OPENVPN  
 
  - name: create client conf
    copy:
      dest: /etc/openvpn/client.conf
      mode: 0644  
      group: root
      owner: root
      content: |    
          dev tap
          remote 192.168.56.10
          ifconfig 10.10.10.2 255.255.255.0
          topology subnet
          route 192.168.56.0 255.255.255.0
          secret /etc/openvpn/static.key
          comp-lzo
          status /var/log/openvpn-status.log
          log /var/log/openvpn.log
          verb 3
    when: (ansible_hostname == "client")      