Vagrant.configure(2) do |config|

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "application.yml"
        ansible.host_key_checking = "false"
        ansible.become_user = "root" 
        ansible.compatibility_mode = "2.0"
        ansible.become = true
     end
  
     config.vm.define "DynamicWeb" do |vmconfig| 
      vmconfig.vm.box = 'centos/7'
      vmconfig.vm.hostname = 'DynamicWeb'

      vmconfig.vm.network "forwarded_port", guest: 8083, host: 8083
      vmconfig.vm.network "forwarded_port", guest: 8081, host: 8081
      vmconfig.vm.network "forwarded_port", guest: 8082, host: 8082
      vmconfig.vm.provider "virtualbox" do |vbx|
       vbx.memory = "2048"
       vbx.cpus = "2"
       vbx.customize ["modifyvm", :id, '--audio', 'none']
      end
     end
  
  end
