- name: postgres master/slave
  hosts: all
  handlers:
  - name: RESTART POSTGRES
    service: 
      name: postgresql-14
      state: restarted
  tasks:
  - name: install soft
    ansible.builtin.yum:
      name: 
        - vim
        - python3-pexpect.noarch
        - python3-psycopg2
        - barman-cli
        - https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm 
      state: present

  - name: disable old postgresql module
    shell: dnf -qy module disable postgresql

  - name: install soft
    ansible.builtin.yum:
      name: 
        -  postgresql14-server
      state: present

  - name: start postgres
    service: 
      name:  postgresql-14
      state: started
      enabled:  yes

  - name: disable selinux
    shell: setenforce 0


- name: postgres master configure
  hosts: master
  handlers:
  - name: RESTART POSTGRES
    service: 
      name: postgresql-14
      state: restarted
  tasks:    
  - name: Create replicator user
    become_user: postgres
    postgresql_user:
      name: replication
      password: 'Otus2022!'
      role_attr_flags: REPLICATION 
    ignore_errors: true

  - name: set config 
    ansible.builtin.template:
      src:  "{{item.src}}"
      dest:  "{{item.dest}}"
      mode: 0644
      owner: postgres
      group: postgres
    loop:
      - { src: tempaltes/pg_hba.conf, dest:  /var/lib/pgsql/14/data/pg_hba.conf}
      - { src: tempaltes/postgresql.conf, dest: /var/lib/pgsql/14/data/postgresql.conf}
    notify: RESTART POSTGRES     
 
  - name: check init 
    stat:
      path: /var/lib/pgsql/14/data/pg_stat
    register: stat_result

  - name: initialization setup
    shell: sudo /usr/pgsql-14/bin/postgresql-14-setup initdb
    when: not stat_result.stat.exists

- name: slave configure
  hosts: slave
  handlers:
  - name: RESTART POSTGRES
    service: 
      name: postgresql-14
      state: restarted
  tasks:    
  - name: STOP POSTGRES
    service: 
      name: postgresql-14
      state: stopped

  - name: Remove files from data catalog
    file:
      path: /var/lib/pgsql/14/data/
      state: absent

  - name: copy files from master to slave
    become_user: postgres
    expect:
      command: 'pg_basebackup -h 192.168.56.11 -U  replication -p 5432 -D /var/lib/pgsql/14/data/ -R -P'
      responses: 
        '.*Password*': "Otus2022!"
 
  - name: set config 
    ansible.builtin.template:
      src:  "{{item.src}}"
      dest:  "{{item.dest}}"
      mode: 0644
      owner: postgres
      group: postgres
    loop:
      - { src: tempaltes/pg_hba.conf, dest:  /var/lib/pgsql/14/data/pg_hba.conf}
      - { src: tempaltes/postgresql.conf, dest: /var/lib/pgsql/14/data/postgresql.conf}
    notify: RESTART POSTGRES  

- name: postgres master configure
  hosts: barman
  tasks:  