# Описание параметров ВМ
MACHINES = {
  # Имя DV "pam"
  :master => {
        # VM box
        :box_name => "centos/8",
        # Имя VM
        :vm_name => "master",
        # Количество ядер CPU
        :cpus => 2,
        # Указываем количество ОЗУ (В Мегабайтах)
        :memory => 1024,
        # Указываем IP-адрес для ВМ
        :ip => "192.168.56.11",
  },
  :slave => {
        :box_name => "centos/8",
        :vm_name => "slave",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.56.12",

  },
  :barman => {
        :box_name => "centos/8",
        :vm_name => "barman",
        :cpus => 1,
        :memory => 1024,
        :ip => "192.168.56.13",

  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # Запуск ansible-playbook
      
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "postgres.yml"
          ansible.become_user = "root" 
          ansible.compatibility_mode = "2.0"
          ansible.become = true
        end
      
    end
  end
end
