- name: Configure client
  hosts: all
  become_user: root
  handlers: 
    - name: RESTART SERVICE SSHD
      service:
        name: sshd 
        state: reloaded

    - name: BORG SERVICE
      service:
        name: borg-backup.timer 
        state: restarted
        enabled: yes   
    
    - name: RSYSLOG RESTART 
      service:
        name: rsyslog 
        state: restarted
        enabled: yes   

  tasks:
  - name: Install soft
    yum: 
      name: epel-release, vim, rsyslog 
      
  - name: Open ssh perminition 
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^\s*.?\s*PermitRootLogin'
      line: 'PermitRootLogin yes'
    notify: RESTART SERVICE SSHD  

  - name: Install soft
    yum:    
     name: borgbackup 

  - name: Create borg user
    user:
      name: borg
      state: present
      append: yes
      groups: sshd

  - name: Borg ssh directory
    file:
      dest: /root/.ssh/
      owner: root
      group: root
      state: directory
      mode: 0700 
  
  - name: Borg ssh keypair
    copy:
      src: id_ssh_rsa
      dest: /root/.ssh/id_rsa        
      owner: root
      group: root
      mode: 0600

  - name: Borg log file
    file:  
      dest: /var/log/borg.log       
      owner: root
      group: root
      state: touch
      mode: 0666  

  - name: Borg rsyslog conf
    copy:
      dest: /etc/rsyslog.d/borg.conf
      content: |
        if $programname == 'borg' then /var/log/borg.log
        & stop
      owner: root
      group: root
      mode: 0644
    notify: RSYSLOG RESTART  

  - name: 
    shell: 'ssh-keyscan -H 192.168.56.160 >> /root/.ssh/known_hosts'
  
  - name: Initialisation backup 
    shell: 'borg init --encryption=none borg@192.168.56.160:/var/backup/'
    #ignore_errors: yes 
  - name: Create unit backup
    copy:
     dest:  /etc/systemd/system/borg-backup.service
     content: |
      [Unit]
      Description=Borg Backup

      [Service]
      Type=oneshot

      # Парольная фраза
      Environment="BORG_PASSPHRASE="
      # Репозиторий
      Environment=REPO=borg@192.168.56.160:/var/backup/
      # Что бэкапим
      Environment=BACKUP_TARGET=/etc

      # Создание бэкапа
      ExecStart=/bin/borg create --stats ${REPO}::etc-{now:%%Y-%%m-%%d_%%H:%%M:%%S} ${BACKUP_TARGET}
      # Проверка бэкапа
      ExecStart=/bin/borg check ${REPO}

      # Очистка старых бэкапов
      ExecStart=/bin/borg prune --keep-daily  90 --keep-monthly 12 --keep-yearly  1   ${REPO}
    notify: BORG SERVICE

  - name: Create unit timer
    copy:
     dest:  /etc/systemd/system/borg-backup.timer
     content: |
      [Unit]
      Description=Borg Backup

      [Timer]
      OnUnitActiveSec=5min

      [Install]
      WantedBy=timers.target
    notify: BORG SERVICE


