- name: Configure server
  hosts: backup
  vars:
    - zabbix_conf: |
        PidFile=/var/run/zabbix/zabbix_agentd.pid
        LogFile=/var/log/zabbix/zabbix_agentd.log
        LogFileSize=0
        Server=192.168.56.15
        ListenIP=0.0.0.0
        HostnameItem=system.hostname
        Include=/etc/zabbix/zabbix_agentd.d/*.conf 

  handlers: 
    - name: RESTART SERVICE SSHD
      service:
        name: sshd 
        state: reloaded
    
    - name: RSYSLOG RESTART 
      service:
        name: rsyslog 
        state: restarted
        enabled: yes      

    - name: RESTART SERVICE ZABBIX
      service:
        name: zabbix-agent
        state: restarted    

  tasks:
  - name: add repo zabbix
    copy:
      dest: /etc/yum.repos.d/zabbix.repo
      content: |
          [smb-local-zabbix50]
          name=Samberi Local - Zabbix 5.0 $releasever
          baseurl=https://repo.zabbix.com/zabbix/5.0/rhel/$releasever/$basearch/
          enabled=1
          gpgcheck=0       

  - name: Install soft
    yum: 
      name: '{{item}}'
      state: latest
    loop: 
      - epel-release
      - vim
      - rsyslog
      - borgbackup
      - zabbix-agent


############RSYSLOG###################
  - name: Borg rsyslog conf
    copy:
      dest: /etc/rsyslog.d/borg.conf
      content: |
        if $programname == 'borg' then /var/log/borg.log
        & stop
      owner: root
      group: root
      mode: 0644
    notify: RSYSLOG RESTART 
  
  - name: Borg rsyslog remote conf
    copy:
      dest: /etc/rsyslog.d/borg_remote.conf
      content: |
        *.* @@192.168.56.15:514
      owner: root
      group: root
      mode: 0644
    notify: RSYSLOG RESTART
  ################BORG##########
  - name: Create borg user
    user:
      name: borg
      state: present
      append: yes
      groups: sshd
  - name: Borg zabbix-agent remote conf
    copy:
      dest: /etc/rsyslog.d/zabbix.conf
      content: |
        $ModLoad imfile
        $InputFileName /var/log/zabbix/zabbix-agentd.log
        *.* @@192.168.56.15:514
      owner: root
      group: root
      mode: 0644
    notify: RSYSLOG RESTART 

  - name: Open ssh perminition
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^\s*.?\s*PermitRootLogin'
      line: 'PermitRootLogin yes'
    notify: RESTART SERVICE SSHD  
    
  - name: Create backup directory 
    file:
      dest: /var/backup
      owner: borg
      group: borg
      state: directory
      mode: 0755
  
  - name: Borg ssh directory
    file:
      dest: /home/borg/.ssh
      owner: borg
      group: borg
      state: directory
      mode: 0700

  - name: Borg ssh keypair
    file:
      dest: /home/borg/.ssh/id_ssh_rsa
      owner: borg
      group: borg
      state: touch
      mode: 0600

  - name: Generate keypair 
    ansible.builtin.openssh_keypair:
      path: /home/borg/.ssh/id_ssh_rsa
      owner: borg
      group: borg

  - name: COPY /home/borg/.ssh/authorized_keys
    ansible.builtin.copy:
      src: /home/borg/.ssh/id_ssh_rsa.pub
      dest: /home/borg/.ssh/authorized_keys
      owner: borg
      group: borg
      mode: 0600   
      remote_src: yes

  - name: COPY /home/borg/.ssh/id_ssh_rsa
    ansible.builtin.fetch:
      src: /home/borg/.ssh/id_ssh_rsa
      dest: ./staff/id_ssh_rsa_borg    
      flat: yes
  
##################ZABBIX-AGENT#########################
  - name: ZABBIX CONF
    copy:
      dest: "/etc/zabbix/zabbix_agentd.conf"
      content: "{{ zabbix_conf }}"
    notify: RESTART SERVICE ZABBIX
  
  - name: START ZABBIX
    service: 
      name: zabbix-agent 
      state: started 
      enabled: yes
  - name: GET SERVICES STATUS (for firewalld)
    systemd:
      name: firewalld
    register: firewalld_status

  - name: OPEN ZABBIX PORT
    firewalld:
      port: 10050/tcp
      permanent: yes
      state: enabled
    when: firewalld_status.status.ActiveState == "active"
    notify: RESTART FIREWALLD

            