---
- name: prepare server monitoring
  hosts: monitoring
  vars:
    - zabbix_db_password: password
  handlers: 
    - name: SSHD RELOAD  
      service:
        name: sshd 
        state: reloaded
    
    - name: BORG SERVICE
      service:
        name: borg-backup.timer 
        state: restarted
        enabled: yes   
        

    - name: CHRONYD RESTART
      service:
        name: chronyd 
        state: restarted
    
    - name: RSYSLOG RESTART 
      service:
        name: rsyslog 
        state: restarted
        enabled: yes        
  tasks:
  - name: Open ssh perminition
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^\s*.?\s*PasswordAuthentication'
      line: 'PasswordAuthentication yes'
    notify: SSHD RELOAD 
 

  - name: Chronyd configure
    timezone:
      name: 'Europe/Moscow'
    notify: CHRONYD RESTART  

######### syslog ############
  - name: Install syslog soft
    yum: 
      name: epel-release, vim, rsyslog

   
  - name: Configuration rsyslog   
    blockinfile:
      path: /etc/rsyslog.conf
      block: |
        # Provides UDP syslog reception
        $ModLoad imudp
        $UDPServerRun 514

        # Provides TCP syslog reception
        $ModLoad imtcp
        $InputTCPServerRun 514

        $template RemoteLogs, "/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
        *.* ?RemoteLogs
        & ~
    notify: RSYSLOG RESTART 
####### zabbix #########
  - name: install zabbix
    yum:
      name: "{{item}}"
      state: latest  
    loop:
        - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        - zabbix-server-mysql 
        - zabbix-agent
        - centos-release-scl
        - mariadb-server
        - zabbix-web-mysql-scl
        - zabbix-nginx-conf-scl
        
  - name: start mysql
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes
  
  - name: prepare mysql for zabbix
    shell: "{{item}}"  
    loop:
      - mysql -uroot -e "create database zabbix character set utf8 collate utf8_bin;"
      - mysql -uroot -e "grant all privileges on zabbix.* to zabbix@localhost identified by '{{zabbix_db_password}}';"
      - mysql -uroot -e "set global log_bin_trust_function_creators = 1;"
      - zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p{{zabbix_db_password}} zabbix
      - mysql -uroot -e "set global log_bin_trust_function_creators = 0;"
    ignore_errors: yes  
       
  - name: change config for zabbix
    ansible.builtin.replace:
      dest:  '{{item.path}}' 
      regexp: '{{item.reg}}'
      replace:  '{{item.rep}}'
    loop:
      - { path: '/etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf', reg: '#\s*listen\s*80;', rep: 'listen 80;' }
      - { path: '/etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf', reg: '#\s*server_name\s*example.com;', rep: 'server_name zabbix.local.com;' }
      - { path: '/etc/zabbix/zabbix_server.conf', reg: '#\s*DBPassword=', rep: 'DBPassword={{zabbix_db_password}}' }
      - { path: '/etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf', reg: 'listen.acl_users = apache\s+', rep: 'listen.acl_users = apache,nginx'}
      - { path: '/etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf', reg: '; php_value[date.timezone] = Europe/Riga', rep: 'php_value[date.timezone] = Europe/Moscow'}
  
  - name: open port
    ansible.builtin.firewalld:
      port: '{{item}}/tcp'
      state: enabled
      permanent: yes
    loop:
      - 80
      - 443  

  - name: start service for zabbix
    service:
      name: "{{item}}"
      state: started
      enabled: yes
    loop: 
      - zabbix-server
      - zabbix-agent
      - rh-nginx116-nginx
      - rh-php72-php-fpm       
####### borg #########
  - name: Install soft
    yum:    
     name: borgbackup 

  - name: Create borg user
    user:
      name: borg
      state: present
      append: yes
      groups: sshd

  - name: Borg ssh directory
    file:
      dest: /root/.ssh/
      owner: root
      group: root
      state: directory
      mode: 0700 
  
  - name: Borg ssh keypair
    copy:
      src: staff/id_ssh_rsa
      dest: /root/.ssh/id_rsa        
      owner: root
      group: root
      mode: 0600

  - name: Borg log file
    file:  
      dest: /var/log/borg.log       
      owner: root
      group: root
      state: touch
      mode: 0666  
 

  - name:  Add keypair known host
    shell: 'ssh-keyscan -H 192.168.56.20 >> /root/.ssh/known_hosts'
  
  - name: Initialisation backup 
    shell: 'borg init --encryption=none borg@192.168.56.20:/var/backup/'
    #ignore_errors: yes 
  - name: Create unit backup
    copy:
     dest:  /etc/systemd/system/borg-backup.service
     content: |
      [Unit]
      Description=Borg Backup

      [Service]
      Type=oneshot

      # Парольная фраза
      Environment="BORG_PASSPHRASE="
      # Репозиторий
      Environment=REPO=borg@192.168.56.20:/var/backup/
      # Что бэкапим
      Environment=BACKUP_TARGET=/etc

      # Создание бэкапа
      ExecStart=/bin/borg create --stats ${REPO}::etc-{now:%%Y-%%m-%%d_%%H:%%M:%%S} ${BACKUP_TARGET}
      # Проверка бэкапа
      ExecStart=/bin/borg check ${REPO}

      # Очистка старых бэкапов
      ExecStart=/bin/borg prune --keep-daily  90 --keep-monthly 12 --keep-yearly  1   ${REPO}
    notify: BORG SERVICE

  - name: Create unit timer
    copy:
     dest:  /etc/systemd/system/borg-backup.timer
     content: |
      [Unit]
      Description=Borg Backup

      [Timer]
      OnUnitActiveSec=5min

      [Install]
      WantedBy=timers.target
    notify: BORG SERVICE


