---
- name: Configure server
  hosts: all #,pxeserver
  handlers:
  - name: HTTPD RESTART
    service:
      name: httpd
      state: restarted
      enabled: true
  - name: TFTP RESTART
    service:
      name: tftp
      state: restarted
      enabled: true   
  - name: DHCP RESTART
    service:
      name: dhcpd
      state: restarted
      enabled: true     
  tasks:
  - name: Set up repo
    replace:
      path: "{{ item }}"
      regexp: 'mirrorlist'
      replace: '#mirrorlist'
    with_items:
      - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo

  - name: Set up repo
    replace:
      path: "{{ item }}"
      regexp: '#baseurl=http://mirror.centos.org'
      replace: 'baseurl=http://vault.centos.org'
    with_items:
      - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo

  - name: Install soft
    ansible.builtin.yum:
      name: httpd, vim, epel-release, tftp-server, dhcp-server
      update_cache: true

  # - name: Download /iso
  #   copy: 
  #     src: /vagrant/CentOS-8.4.2105-x86_64-dvd1.iso
  #     dest: ~/CentOS-8.4.2105-x86_64-dvd1.iso
  #     mode: 0755
  #     remote_src: yes

  # - name: Download /iso
  #   ansible.builtin.get_url:
  #     validate_certs: false
  #     url: 'https://mirror.sale-dedic.com/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso'
  #     dest: ~/CentOS-8.4.2105-x86_64-dvd1.iso
  #     mode: 0755

  - name: Create directory iso
    file:
      path: /iso
      state: directory
      owner:
      group:
      mode: 0755   
  - name: Mount iso
    mount:
      path: /mnt
      src: ~/CentOS-8.4.2105-x86_64-dvd1.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted

  - name: Copy files
    copy:
      src: /mnt/
      dest: /iso/
      directory_mode: yes
      remote_src: yes

  - name: Configure httpd
    ansible.builtin.copy:
      dest: /etc/httpd/conf.d/pxeboot.conf 
      content: |
        Alias /centos8 /iso
          #Указываем адрес директории /iso
          <Directory /iso>
              Options Indexes FollowSymLinks
              #Разрешаем подключения со всех ip-адресов
              Require all granted
    notify: HTTPD RESTART

  - name: Create TFTP directory
    file:
      path: /var/lib/tftpboot/
      state: directory
      mode: '0755'

  - name: Create pxelinux.cfg directory
    file:
      path: /var/lib/tftpboot/pxelinux.cfg
      state: directory
      mode: '0755'

  - name: Configure tftp
    ansible.builtin.copy:
      dest: /var/lib/tftpboot/pxelinux.cfg/default
      content: |
        default menu.c32
        prompt 0
        #Время счётчика с обратным отсчётом (установлено 15 секунд)
        timeout 150
        #Параметр использования локального времени
        ONTIME local
        #Имя «шапки» нашего меню
        menu title OTUS PXE Boot Menu
              #Описание первой строки
              label 1
              #Имя, отображаемое в первой строке
              menu label ^ Graph install CentOS 8.4
              #Адрес ядра, расположенного на TFTP-сервере
              kernel /vmlinuz
              #Адрес файла initrd, расположенного на TFTP-сервере
              initrd /initrd.img
              #Получаем адрес по DHCP и указываем адрес веб-сервера
              append ip=enp0s3:dhcp inst.repo=http://10.0.0.20/centos8
              label 2
              menu label ^ Text install CentOS 8.4
              kernel /vmlinuz
              initrd /initrd.img
              append ip=enp0s3:dhcp inst.repo=http://10.0.0.20/centos8 text
              label 3
              menu label ^ rescue installed system
              kernel /vmlinuz
              initrd /initrd.img
              append ip=enp0s3:dhcp inst.repo=http://10.0.0.20/centos8 rescue
    notify: TFTP RESTART
  
  - name: Exctract rpm
    shell: 'rpm2cpio /iso/mnt/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv'
  
  - name: Copy file libreres
    copy:
      src:  '/home/vagrant/tftpboot/{{item}}'
      dest: '/var/lib/tftpboot/{{item}}'
      remote_src: yes
      mode: '0644'
    with_items:
      - pxelinux.0
      - ldlinux.c32
      - libmenu.c32
      - libutil.c32
      - menu.c32
      - vesamenu.c32
    notify: TFTP RESTART 

  - name: Copy file libreres
    copy:
      src:  '/iso/images/pxeboot/{{item}}'
      dest: '/var/lib/tftpboot/{{item}}'
      remote_src: yes
      mode: '0755'
    with_items:
      - initrd.img
      - vmlinuz
    notify: TFTP RESTART

  - name: Configure dhcp
    ansible.builtin.copy:
      dest: /etc/dhcp/dhcpd.conf
      content: |    
          option space pxelinux;
          option pxelinux.magic code 208 = string;
          option pxelinux.configfile code 209 = text;
          option pxelinux.pathprefix code 210 = text;
          option pxelinux.reboottime code 211 = unsigned integer 32;
          option architecture-type code 93 = unsigned integer 16;

          #Указываем сеть и маску подсети, в которой будет работать DHCP-сервер
          subnet 10.0.0.0 netmask 255.255.255.0 {
                  #Указываем шлюз по умолчанию, если потребуется
                  #option routers 10.0.0.1;
                  #Указываем диапазон адресов
                  range 10.0.0.100 10.0.0.120;

                  class "pxeclients" {
                    match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
                    #Указываем адрес TFTP-сервера
                    next-server 10.0.0.20;
                    #Указываем имя файла, который надо запустить с TFTP-сервера
                    filename "pxelinux.0";
                  }
           }       
    notify: DHCP RESTART