# docker-compose.yml
version: '3.0'

services:
  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: myrootpw
      MYSQL_DATABASE: gallery3
      MYSQL_USER: gallery3
      MYSQL_PASSWORD: mygallery3pw
    ports:
       - 3306:3306
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
      - ./mysql:/var/lib/mysql
  gallery3:
    image: bwdutton/gallery3
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
# set these if you wish to use the CLI installer, otherwise you enter them on the web
      MYSQL_ROOT_PASSWORD: myrootpw
      MYSQL_DATABASE: gallery3
      MYSQL_USER: gallery3
      MYSQL_PASSWORD: mygallery3pw
      MYSQL_HOST: mysql
      G3_PASSWORD:
      DB_PREFIX:
      SITE_DOMAIN:
      SITE_PROTOCOL:
    ports:
      - "8080:80"
    volumes:
      - ./gallery-var:/var/www/html/var
  nginx: 
      image: nginx:1.21
      volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl 
      extra_hosts:
        - "gallery.local.com:192.168.56.{% if ansible_hostname == 'back' %}10{%elif ansible_hostname == 'front'%}5{% endif %}"
      ports:
       - 443:443
       - 80:80    
