- name: configure replication mysql
  hosts: all
  handlers:
  - name: RESTART MYSQL 
    service:
      name: mysqld
      state: restarted
  tasks:
  - name: copy rpm
    ansible.builtin.copy:
      src: '{{item}}'
      dest: './{{item}}'
      owner: root
      group: root
      mode: 0644
    loop:
      - Percona-Server-shared-compat-57-5.7.44-48.1.el7.x86_64.rpm
      - Percona-Server-shared-57-5.7.44-48.1.el7.x86_64.rpm
      - Percona-Server-client-57-5.7.44-48.1.el7.x86_64.rpm
      - Percona-Server-server-57-5.7.44-48.1.el7.x86_64.rpm  
      
  - name: install soft
    yum:
      name: 
      - MySQL-python
      - vim
      - Percona-Server-shared-compat-57-5.7.44-48.1.el7.x86_64.rpm
      - Percona-Server-shared-57-5.7.44-48.1.el7.x86_64.rpm
      - Percona-Server-client-57-5.7.44-48.1.el7.x86_64.rpm
      - Percona-Server-server-57-5.7.44-48.1.el7.x86_64.rpm     
      state: present 
      update_cache: yes
      
  - name: copy configure
    ansible.builtin.template:
      src: ./conf/{{item}}
      dest: /etc/my.cnf.d/{{item}}
      owner:  root
      group: root
      mode: 0644
    loop: 
      - '01-base.cnf'
      - '02-max-connections.cnf'
      - '04-slow-query.cnf'
      - '03-performance.cnf'
      - '05-binlog.cnf'
    notify: RESTART MYSQL 

  - name: START MYSQL 
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: get password root mysql
    shell: "cat /var/log/mysqld.log | grep 'root@localhost:' | awk '{print $11}'"
    register: mysql_pswd

  - name: set new password sql
    shell: mysql -uroot -e 'ALTER USER USER() IDENTIFIED BY "Otus2023!";' -p'{{mysql_pswd.stdout_lines[0]}}' --connect-expired-password
    ignore_errors: yes

  - name: create user in db
    ansible.builtin.mysql_user:
      name: repl
      password: '!OtusLinux2018'
      host: '%' 
      login_user: root
      login_password: "Otus2023!"
      priv: "*.*:REPLICATION SLAVE"
      state: present  

- name: configure master
  hosts: master
  tasks:
  - name: create db
    mysql_db:
      name: bet
      state: present
      login_user: root
      login_password: "Otus2023!" 

  - name: copy db bet 
    ansible.builtin.copy:
      src: bet.dmp
      dest: ./
  
  - name: import db
    ansible.builtin.mysql_db:
      name: bet
      state: import
      target: bet.dmp
      login_user: root
      login_password: "Otus2023!"

  - name: backup db
    shell: 'mysqldump --all-databases --triggers --routines --master-data --set-gtid-purged=off --ignore-table=bet.events_on_demand --ignore-table=bet.v_same_event -uroot -pOtus2023! > master.sql'  
  
  - name: fetch db
    ansible.builtin.fetch:
      src: master.sql
      dest: ./
      flat: yes

- name: configure slave
  hosts: slave
  tasks:
  - name: copy db bet 
    ansible.builtin.copy:
      src: master.sql
      dest: ./
  - name:
    shell: mysql -uroot -pOtus2023! -e "SOURCE /home/vagrant/master.sql"
  # - name: import db
  #   ansible.builtin.mysql_db:
  #     name: bet
  #     state: import
  #     target: master.sql
  #     login_user: root
  #     login_password: "Otus2023!"

  - name: setting slave
    shell: mysql -uroot -pOtus2023! -e "CHANGE MASTER TO MASTER_HOST = '192.168.56.150', MASTER_PORT = 3306,MASTER_USER = 'repl', MASTER_PASSWORD = '!OtusLinux2018', MASTER_AUTO_POSITION = 1;"  

  - name: setting slave
    shell: mysql -uroot -pOtus2023! -e "START SLAVE;"    
   